apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod #name of pod
  labels:
    name: postgres-pod #labels are refered by services lated
    app: demo-voting-app
#same format of labels using for all services
spec:
  containers:
    - name: postgres
      image: posstgres:9.4
      ports:
        - containerPort: 5432 #default postgres listening port