apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service #for result labels not needed but good practice
    app: demo-voting-app #still the same name for all app
spec:
  type: LoadBalancer #default is ClusterIP but we want the service to be accesible form outside
  ports:
    - port: 80
      targetPort: 80
      #listen and forward port to pod for services filtered by selector
  selector:
    name: result-app-pod 
    app: demo-voting-app


