apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod #name of pod
  labels:
    name: result-app-pod #labels are refered by services lated
    app: demo-voting-app
#same format of labels using for all services
spec:
  containers:
    - name: result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80 #exposes port 80 it is web application