apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app #still the same name for all app
spec:
  type: LoadBalancer #default is ClusterIP but we want the service to be accesible form outside
  ports:
    - port: 80
      targetPort: 80
      #listen and forward port to pod for services filtered by selector
  selector:
    name: voting-app-pod
    app: demo-voting-app


