apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod #name of pod
  labels:
    name: voting-app-pod #labels are refered by services lated
    app: demo-voting-app
#same format of labels using for all services
spec:
  containers:
    - name: voting-app
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80