apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod #labels are refered by services lated
      app: demo-voting-app
  template:

