apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-app-pod #labels are refered by services lated
      app: demo-voting-app
  template:
    metadata:
      name: worker-app-pod #name of pod
      labels:
        name: worker-app-pod #labels are refered by services lated
        app: demo-voting-app
    #same format of labels using for all services
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker



